apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: movies
  region: us-east-1

managedNodeGroups:
  - name: react-flask-pg-node
    instanceType: t3.small
    desiredCapacity: 3
    minSize: 1
    maxSize: 3
    volumeSize: 20 #min size
    spot: true
